import type { Metadata } from "next";
import { Nunito} from "next/font/google";
import Navbar from "@/app/components/Navbar/Navbar"
import "./globals.css";
import RegisterModel from "./components/Model/RegisterModel";


const font = Nunito({
  subsets:['latin']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className = {font.className}>
        <RegisterModel/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
